-- CMS V2 data model:
-- - locale-aware documents
-- - queryable dimensions (page_id, block_id, locale, doc_type, status)
-- - version history per document
--
-- This migration is additive and backward compatible with existing
-- `global_settings`-based CMS runtime.

create table if not exists public.cms_documents (
  id bigint generated by default as identity primary key,
  page_id text not null,
  block_id text null,
  block_scope text generated always as (coalesce(block_id, '__page__')) stored,
  locale text not null default 'default',
  doc_type text not null check (doc_type in ('page_config', 'text_overrides', 'design_tokens', 'custom_css')),
  status text not null default 'published' check (status in ('draft', 'published', 'archived')),
  current_version_id bigint null,
  created_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (page_id, block_scope, locale, doc_type)
);

create table if not exists public.cms_document_versions (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.cms_documents(id) on delete cascade,
  version int not null,
  content jsonb not null default '{}'::jsonb,
  note text null,
  created_by uuid null,
  created_at timestamptz not null default now(),
  unique (document_id, version)
);

-- Add FK after version table exists.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'cms_documents_current_version_id_fkey'
  ) then
    alter table public.cms_documents
      add constraint cms_documents_current_version_id_fkey
      foreign key (current_version_id)
      references public.cms_document_versions(id)
      on delete set null;
  end if;
end $$;

create index if not exists idx_cms_documents_lookup
  on public.cms_documents (page_id, locale, doc_type, status);

create index if not exists idx_cms_documents_block_lookup
  on public.cms_documents (page_id, block_scope, locale, doc_type);

create index if not exists idx_cms_document_versions_document
  on public.cms_document_versions (document_id, version desc);

create index if not exists idx_cms_document_versions_content_gin
  on public.cms_document_versions
  using gin (content jsonb_path_ops);

create or replace function public.cms_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_cms_documents_set_updated_at on public.cms_documents;
create trigger trg_cms_documents_set_updated_at
before update on public.cms_documents
for each row
execute function public.cms_set_updated_at();
