-- First, add any missing cities that may be needed for the hotels
INSERT INTO cities (name, slug, is_active, is_featured)
VALUES 
  ('Armação de Pêra', 'armacao-de-pera', true, false),
  ('Loulé', 'loule', true, false),
  ('Porches', 'porches', true, false)
ON CONFLICT (slug) DO NOTHING;
-- Seed 58 5-star hotels from Booking.com
WITH category_ref AS (
  SELECT id FROM categories WHERE slug = 'premium-accommodation' LIMIT 1
),
city_refs AS (
  SELECT id, name, slug FROM cities
),
owner_ref AS (
  SELECT '280be9b4-c0fe-48f3-b371-f490d8cccfd5'::uuid as owner_id
)
INSERT INTO listings (name, slug, description, short_description, owner_id, category_id, city_id, tier, status, is_curated, category_data)
SELECT 
  hotel.name,
  hotel.slug,
  hotel.description,
  hotel.short_description,
  o.owner_id,
  c.id,
  (SELECT id FROM city_refs WHERE slug = hotel.city_slug LIMIT 1),
  'unverified'::listing_tier,
  'published'::listing_status,
  false,
  hotel.category_data::jsonb
FROM category_ref c, owner_ref o,
(VALUES
  -- Page 1 Hotels (1-25)
  ('Real Santa Eulália Hotel & Spa', 'real-santa-eulalia-hotel-spa', 'Premium 5-star beachfront resort in Albufeira with exceptional facilities, spa, and direct beach access. Perfect for families and couples seeking a premium Algarve experience.', 'Premium beachfront resort with spa and premium amenities.', 'albufeira', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Swimming Pool", "Spa", "Beach Access", "Restaurant", "Fitness Center", "Kids Club"], "room_types": ["Deluxe Room", "Suite", "Family Room"], "check_in_time": "15:00", "check_out_time": "11:00"}'),
  
  ('Vilalara Thalassa Resort', 'vilalara-thalassa-resort', 'Award-winning adults-only premium resort in Lagoa featuring Thalassotherapy spa, organic gardens, and stunning clifftop location overlooking the Atlantic Ocean.', 'Award-winning adults-only resort with Thalassotherapy spa.', 'lagoa', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Thalassotherapy Spa", "Swimming Pool", "Private Beach", "Organic Restaurant", "Tennis Courts", "Yoga Studio"], "room_types": ["Ocean View Suite", "Garden Suite", "Presidential Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Pestana Alvor Praia', 'pestana-alvor-praia', 'Premium cliff-top hotel in Alvor with panoramic sea views, multiple pools, and excellent dining. Ideal location for exploring the beautiful Alvor coastline.', 'Cliff-top hotel with panoramic sea views and multiple pools.', 'alvor', '{"star_rating": 5, "property_type": "Hotel", "amenities": ["Infinity Pool", "Spa", "Private Beach", "Multiple Restaurants", "Tennis Courts", "Gym"], "room_types": ["Sea View Room", "Premium Suite", "Deluxe Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('EPIC SANA Algarve Hotel', 'epic-sana-algarve-hotel', 'Contemporary 5-star resort in Albufeira offering spacious suites, SAYANNA Wellness center, and family-friendly facilities amid Mediterranean gardens.', 'Contemporary resort with wellness center and family facilities.', 'albufeira', '{"star_rating": 5, "property_type": "Resort", "amenities": ["SAYANNA Wellness", "5 Swimming Pools", "Kids Club", "Multiple Restaurants", "Golf Nearby", "Fitness Center"], "room_types": ["Deluxe Suite", "Family Suite", "Grand Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Vila Vita Parc Resort & Spa', 'vila-vita-parc-resort-spa', 'Iconic 5-star resort in Porches set on 54 acres of landscaped gardens. Home to 2-Michelin star Ocean restaurant, private yacht, and exclusive Oasis Parc.', 'Iconic resort with 2-Michelin star restaurant and private yacht.', 'lagoa', '{"star_rating": 5, "property_type": "Resort", "amenities": ["2 Michelin Star Restaurant", "Private Yacht", "Spa", "Golf Course", "Tennis Academy", "Kids Club", "Private Beach"], "room_types": ["Ocean Suite", "Villa", "Residence", "Grand Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Longevity Health & Wellness Hotel', 'longevity-health-wellness-hotel', 'Boutique wellness hotel in Alvor dedicated to health, longevity, and wellbeing. Features cutting-edge medical spa, organic cuisine, and personalized wellness programs.', 'Boutique wellness hotel with medical spa and organic cuisine.', 'alvor', '{"star_rating": 5, "property_type": "Wellness Hotel", "amenities": ["Medical Spa", "Organic Restaurant", "Yoga Studio", "Detox Programs", "Swimming Pool", "Gym"], "room_types": ["Wellness Room", "Superior Room", "Suite"], "check_in_time": "15:00", "check_out_time": "11:00"}'),
  
  ('Macdonald Monchique Resort & Spa', 'macdonald-monchique-resort-spa', 'Mountain retreat in the Serra de Monchique offering tranquility, thermal spa, and stunning panoramic views of the Algarve coastline from elevated position.', 'Mountain retreat with thermal spa and panoramic views.', 'monchique', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Thermal Spa", "Swimming Pool", "Restaurant", "Hiking Trails", "Tennis", "Kids Activities"], "room_types": ["Mountain View Suite", "Deluxe Room", "Villa"], "check_in_time": "15:00", "check_out_time": "11:00"}'),
  
  ('Tivoli Marina Vilamoura', 'tivoli-marina-vilamoura', 'Prestigious hotel overlooking Vilamoura Marina with direct access to the beach, world-class golf courses nearby, and vibrant nightlife at your doorstep.', 'Prestigious marina-front hotel with golf and beach access.', 'vilamoura', '{"star_rating": 5, "property_type": "Hotel", "amenities": ["Marina Views", "Swimming Pool", "Spa", "Multiple Restaurants", "Casino Nearby", "Golf Concierge"], "room_types": ["Marina View Room", "Premium Suite", "Presidential Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('The Westin Resort Salgados Beach', 'westin-resort-salgados-beach', 'Modern resort on Salgados Beach featuring signature Heavenly Beds, WestinWORKOUT studio, and direct access to pristine beach and golf courses.', 'Modern beachfront resort with direct beach and golf access.', 'albufeira', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Private Beach", "Heavenly Spa", "Golf Course", "Swimming Pools", "Kids Club", "Tennis Courts"], "room_types": ["Heavenly Room", "Premium Suite", "Beach Villa"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('3HB Faro Marina', 'three-hb-faro-marina', 'Stylish urban hotel in Faro Marina offering contemporary design, rooftop pool, and convenient access to Ria Formosa Natural Park and Faro Old Town.', 'Stylish urban hotel with rooftop pool overlooking the marina.', 'faro', '{"star_rating": 5, "property_type": "Boutique Hotel", "amenities": ["Rooftop Pool", "Marina Views", "Restaurant", "Bar", "Gym", "Meeting Rooms"], "room_types": ["Premium Room", "Suite", "Marina Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('Domes Lake Algarve', 'domes-lake-algarve', 'All-suite premium resort near Vilamoura featuring private pools, Greek-inspired design, and serene lake setting. Perfect for couples and families alike.', 'All-suite premium resort with private pools and lake setting.', 'vilamoura', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Private Pools", "Spa", "Kids Club", "Multiple Restaurants", "Beach Shuttle", "Wellness Center"], "room_types": ["Pavilion Suite", "Premium Suite", "Sapphire Villa"], "check_in_time": "15:00", "check_out_time": "11:00"}'),
  
  ('Tivoli Carvoeiro Algarve Resort', 'tivoli-carvoeiro-algarve-resort', 'Clifftop resort in Carvoeiro with dramatic ocean views, award-winning spa, and access to stunning beaches and caves of the western Algarve.', 'Clifftop resort with dramatic ocean views and award-winning spa.', 'carvoeiro', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Clifftop Location", "Anazoe Spa", "Swimming Pools", "Beach Access", "Golf Nearby", "Tennis"], "room_types": ["Ocean View Room", "Premium Suite", "Villa"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Salgados Palace', 'salgados-palace', 'Grand resort in Albufeira featuring palatial architecture, extensive spa facilities, championship golf course, and family-friendly amenities.', 'Grand resort with palatial architecture and championship golf.', 'albufeira', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Championship Golf", "Spa", "Multiple Pools", "Kids Club", "Restaurants", "Conference Center"], "room_types": ["Deluxe Room", "Suite", "Family Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('Vale d''Oliveiras Quinta Resort & Spa', 'vale-d-oliveiras-quinta-resort-spa', 'Boutique resort in Carvoeiro surrounded by olive groves, featuring organic spa, farm-to-table dining, and peaceful countryside ambiance.', 'Boutique resort surrounded by olive groves with organic spa.', 'carvoeiro', '{"star_rating": 5, "property_type": "Boutique Resort", "amenities": ["Organic Spa", "Olive Groves", "Farm Restaurant", "Pool", "Tennis", "Yoga"], "room_types": ["Garden Suite", "Olive Suite", "Villa"], "check_in_time": "15:00", "check_out_time": "11:00"}'),
  
  ('Anantara Vilamoura Algarve Resort', 'anantara-vilamoura-algarve-resort', 'Asian-inspired premium resort in Vilamoura offering world-class golf, Anantara Spa, and sophisticated dining experiences in elegant surroundings.', 'Asian-inspired premium resort with world-class golf and spa.', 'vilamoura', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Anantara Spa", "5 Golf Courses", "Swimming Pools", "Fine Dining", "Kids Club", "Beach Club"], "room_types": ["Deluxe Room", "Premium Suite", "Pool Villa"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Pestana Blue Alvor', 'pestana-blue-alvor', 'All-inclusive adults-only resort in Alvor with modern design, beachfront location, and comprehensive wellness facilities for the ultimate relaxation.', 'All-inclusive adults-only beachfront resort.', 'alvor', '{"star_rating": 5, "property_type": "Resort", "amenities": ["All-Inclusive", "Adults Only", "Beach Access", "Spa", "Multiple Restaurants", "Entertainment"], "room_types": ["Premium Room", "Suite", "Pool Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('São Rafael Suites', 'sao-rafael-suites', 'All-suite premium resort on São Rafael Beach featuring spacious accommodations, water park, and excellent family facilities in prime Albufeira location.', 'All-suite resort with water park on São Rafael Beach.', 'albufeira', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Water Park", "Private Beach", "All-Inclusive Option", "Kids Club", "Spa", "Multiple Restaurants"], "room_types": ["Junior Suite", "Family Suite", "Presidential Suite"], "check_in_time": "15:00", "check_out_time": "11:00"}'),
  
  ('Hotel Algarve Casino', 'hotel-algarve-casino', 'Landmark hotel in Praia da Rocha with stunning beach views, casino entertainment, and vibrant atmosphere near Portimão marina and nightlife.', 'Landmark hotel with casino entertainment and beach views.', 'praia-da-rocha', '{"star_rating": 5, "property_type": "Hotel", "amenities": ["Casino", "Beach Access", "Swimming Pool", "Spa", "Multiple Restaurants", "Nightclub"], "room_types": ["Sea View Room", "Suite", "Penthouse"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('Viceroy at Ombria Algarve', 'viceroy-at-ombria-algarve', 'Ultra-premium resort in the Algarve hinterland featuring sustainable design, championship golf, and exclusive villas amid rolling hills and cork oak forests.', 'Ultra-premium resort with sustainable design and golf.', 'loule', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Championship Golf", "Spa", "Infinity Pool", "Farm-to-Table Restaurant", "Nature Trails", "Tennis"], "room_types": ["Deluxe Room", "Suite", "Private Villa"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Kimpton Atlântico Algarve', 'kimpton-atlantico-algarve', 'Boutique premium hotel in Portimão with distinctive art-deco design, rooftop bar, and personalized service in a prime waterfront location.', 'Boutique hotel with art-deco design and rooftop bar.', 'portimao', '{"star_rating": 5, "property_type": "Boutique Hotel", "amenities": ["Rooftop Bar", "Swimming Pool", "Spa", "Restaurant", "Gym", "Concierge"], "room_types": ["Premium Room", "Junior Suite", "Penthouse Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Sheraton Algarve Hotel', 'sheraton-algarve-hotel', 'Prestigious resort at Pine Cliffs in Albufeira featuring iconic location, exceptional golf, and family-friendly amenities overlooking the Atlantic.', 'Prestigious Pine Cliffs resort with golf and family amenities.', 'albufeira', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Pine Cliffs Golf", "Private Beach", "Spa", "Multiple Restaurants", "Kids Club", "Tennis Academy"], "room_types": ["Pine View Room", "Ocean Suite", "Villa"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('W Algarve', 'w-algarve', 'Ultra-hip lifestyle hotel in Albufeira with cutting-edge design, WET deck infinity pool, and vibrant social scene at the signature WooBar.', 'Ultra-hip lifestyle hotel with infinity pool and WooBar.', 'albufeira', '{"star_rating": 5, "property_type": "Hotel", "amenities": ["WET Deck", "Away Spa", "WooBar", "Infinity Pool", "Restaurant", "DJ Events"], "room_types": ["Wonderful Room", "Spectacular Suite", "WOW Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Onyria Palmares Beach House Hotel', 'onyria-palmares-beach-house-hotel', 'Contemporary beach hotel in Lagos with direct beach access, Palmares Golf course, and modern design celebrating the beauty of the western Algarve.', 'Contemporary beach hotel with golf and modern design.', 'lagos', '{"star_rating": 5, "property_type": "Beach Hotel", "amenities": ["Private Beach", "Palmares Golf", "Spa", "Infinity Pool", "Restaurant", "Yoga"], "room_types": ["Beach Room", "Ocean Suite", "Penthouse"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Crowne Plaza Vilamoura', 'crowne-plaza-vilamoura', 'Modern business and leisure hotel in Vilamoura with conference facilities, spa, and convenient location near the marina and golf courses.', 'Modern hotel with conference facilities near marina.', 'vilamoura', '{"star_rating": 5, "property_type": "Hotel", "amenities": ["Conference Center", "Spa", "Swimming Pool", "Restaurant", "Golf Nearby", "Fitness Center"], "room_types": ["Deluxe Room", "Executive Suite", "Club Room"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Conrad Algarve', 'conrad-algarve', 'Sophisticated 5-star resort in Quinta do Lago featuring world-class golf, premium spa, and refined dining in the heart of the Golden Triangle.', 'Sophisticated resort in Quinta do Lago''s Golden Triangle.', 'quinta-do-lago', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Golf Courses", "Spa", "Michelin Restaurant", "Swimming Pool", "Kids Club", "Tennis"], "room_types": ["Deluxe Room", "Premium Suite", "Royal Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  -- Additional Hotels (26-58)
  ('The Lake Resort', 'the-lake-resort', 'Elegant lakeside resort in Vilamoura offering stunning views, comprehensive wellness facilities, and proximity to world-class golf courses.', 'Elegant lakeside resort with wellness facilities.', 'vilamoura', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Lake Views", "Spa", "Golf Nearby", "Swimming Pool", "Restaurant", "Tennis"], "room_types": ["Lake View Room", "Suite", "Villa"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Pine Cliffs Hotel', 'pine-cliffs-hotel', 'Iconic resort perched on red cliffs in Albufeira with direct beach access via cliff elevator, 9-hole golf course, and extensive family facilities.', 'Iconic clifftop resort with elevator beach access.', 'albufeira', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Cliff Elevator", "Private Beach", "Golf Course", "Kids Club", "Multiple Restaurants", "Spa"], "room_types": ["Garden View", "Ocean View Suite", "Residence"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Martinhal Sagres Beach Family Resort', 'martinhal-sagres-beach-family-resort', 'Award-winning family resort in Sagres combining premium accommodations with exceptional kids facilities and stunning natural setting near Cape St. Vincent.', 'Award-winning family resort near Cape St. Vincent.', 'sagres', '{"star_rating": 5, "property_type": "Family Resort", "amenities": ["Kids Club", "Water Sports", "Beach Access", "Spa", "Multiple Restaurants", "Tennis"], "room_types": ["Beach House", "Bay House", "Villa"], "check_in_time": "15:00", "check_out_time": "11:00"}'),
  
  ('NAU São Rafael Atlântico', 'nau-sao-rafael-atlantico', 'All-inclusive family resort on São Rafael Beach with water park, entertainment, and extensive facilities for an action-packed holiday.', 'All-inclusive family resort with water park.', 'albufeira', '{"star_rating": 5, "property_type": "Resort", "amenities": ["All-Inclusive", "Water Park", "Kids Club", "Beach Access", "Spa", "Entertainment"], "room_types": ["Standard Room", "Family Room", "Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('Hilton Vilamoura As Cascatas Golf Resort & Spa', 'hilton-vilamoura-as-cascatas', 'Spacious resort in Vilamoura featuring cascading pools, comprehensive spa, and convenient access to premium golf courses and marina.', 'Spacious resort with cascading pools and golf access.', 'vilamoura', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Cascading Pools", "Spa", "Golf Concierge", "Kids Club", "Multiple Restaurants", "Tennis"], "room_types": ["Deluxe Room", "Family Suite", "Executive Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Hotel Quinta do Lago', 'hotel-quinta-do-lago', 'Exclusive boutique hotel in the prestigious Quinta do Lago estate offering refined elegance, championship golf, and access to Ria Formosa Nature Reserve.', 'Exclusive boutique hotel in prestigious Quinta do Lago.', 'quinta-do-lago', '{"star_rating": 5, "property_type": "Boutique Hotel", "amenities": ["Golf Courses", "Spa", "Lake Access", "Fine Dining", "Tennis", "Cycling"], "room_types": ["Deluxe Room", "Premium Suite", "Lake Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Dona Filipa Hotel', 'dona-filipa-hotel', 'Classic premium hotel in Vale do Lobo with timeless elegance, San Lorenzo Golf course access, and sophisticated atmosphere in the Golden Triangle.', 'Classic premium hotel with San Lorenzo Golf access.', 'vale-do-lobo', '{"star_rating": 5, "property_type": "Hotel", "amenities": ["San Lorenzo Golf", "Swimming Pool", "Spa", "Fine Dining", "Tennis", "Beach Club"], "room_types": ["Classic Room", "Deluxe Suite", "Presidential Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('Ria Park Hotel & Spa', 'ria-park-hotel-spa', 'Contemporary hotel in Vale do Lobo featuring modern design, comprehensive spa, and outstanding location between golf courses and beach.', 'Contemporary hotel with spa between golf and beach.', 'vale-do-lobo', '{"star_rating": 5, "property_type": "Hotel", "amenities": ["Spa", "Swimming Pool", "Golf Nearby", "Restaurant", "Beach Access", "Gym"], "room_types": ["Standard Room", "Premium Room", "Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Bela Vista Hotel & Spa', 'bela-vista-hotel-spa', 'Boutique historic hotel in Portimão''s Praia da Rocha with stunning cliff-top views, intimate spa, and charming period architecture.', 'Boutique historic hotel with cliff-top views.', 'praia-da-rocha', '{"star_rating": 5, "property_type": "Boutique Hotel", "amenities": ["Cliff Views", "Spa", "Beach Access", "Fine Dining", "Pool", "Historic Architecture"], "room_types": ["Classic Room", "Sea View Suite", "Romantic Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Jupiter Marina Hotel', 'jupiter-marina-hotel', 'Modern hotel in Portimão Marina with rooftop pool, marina views, and excellent access to beaches, restaurants, and the Arade River.', 'Modern hotel with rooftop pool and marina views.', 'portimao', '{"star_rating": 5, "property_type": "Hotel", "amenities": ["Rooftop Pool", "Marina Views", "Spa", "Restaurant", "Gym", "Conference Rooms"], "room_types": ["City View", "Marina View", "Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('Monte Santo Resort', 'monte-santo-resort', 'Family-friendly resort in Carvoeiro with spacious suites, beautiful gardens, and excellent location near beaches and local attractions.', 'Family-friendly resort with spacious suites.', 'carvoeiro', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Gardens", "Multiple Pools", "Kids Club", "Restaurant", "Spa", "Tennis"], "room_types": ["Garden Suite", "Pool View Suite", "Family Villa"], "check_in_time": "15:00", "check_out_time": "11:00"}'),
  
  ('Grande Real Santa Eulália Resort & Hotel Spa', 'grande-real-santa-eulalia-resort', 'Grand beachfront resort in Albufeira with extensive facilities, multiple pools, and premium services for families and couples alike.', 'Grand beachfront resort with extensive facilities.', 'albufeira', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Private Beach", "Multiple Pools", "Spa", "Kids Club", "Restaurants", "Golf Nearby"], "room_types": ["Deluxe Room", "Family Suite", "Royal Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('Vidamar Resort Hotel Algarve', 'vidamar-resort-hotel-algarve', 'Modern beachfront resort in Albufeira with sleek design, comprehensive spa, and direct access to Salgados Beach natural reserve.', 'Modern beachfront resort on Salgados Beach.', 'albufeira', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Beach Access", "Spa", "Multiple Pools", "Nature Reserve", "Golf Nearby", "Kids Club"], "room_types": ["Standard Room", "Deluxe Suite", "Penthouse"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('São Rafael Beach Resort', 'sao-rafael-beach-resort', 'Exclusive beachfront resort on São Rafael Beach with all-suite accommodations, premium dining, and family-friendly atmosphere.', 'Exclusive beachfront resort with all-suite accommodations.', 'albufeira', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Private Beach", "All-Suite", "Spa", "Kids Club", "Multiple Restaurants", "Pool"], "room_types": ["Junior Suite", "Deluxe Suite", "Presidential Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('DoubleTree by Hilton Lagos', 'doubletree-by-hilton-lagos', 'Contemporary hotel in Lagos with harbor views, modern amenities, and convenient location for exploring the historic town and nearby beaches.', 'Contemporary hotel with harbor views.', 'lagos', '{"star_rating": 5, "property_type": "Hotel", "amenities": ["Harbor Views", "Swimming Pool", "Restaurant", "Bar", "Gym", "Meeting Rooms"], "room_types": ["Standard Room", "Premium Room", "Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('AP Adriana Beach Resort', 'ap-adriana-beach-resort', 'All-inclusive family resort on Falésia Beach with water park, extensive entertainment, and comprehensive facilities for all ages.', 'All-inclusive family resort with water park.', 'albufeira', '{"star_rating": 5, "property_type": "Resort", "amenities": ["All-Inclusive", "Water Park", "Private Beach", "Kids Club", "Entertainment", "Spa"], "room_types": ["Standard Room", "Family Room", "Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('Cascade Wellness Resort', 'cascade-wellness-resort', 'Boutique wellness resort in Lagos with focus on health, relaxation, and personalized service amid beautiful clifftop gardens.', 'Boutique wellness resort with clifftop gardens.', 'lagos', '{"star_rating": 5, "property_type": "Wellness Resort", "amenities": ["Wellness Center", "Spa", "Yoga", "Organic Restaurant", "Pool", "Gardens"], "room_types": ["Garden Room", "Sea View Room", "Suite"], "check_in_time": "15:00", "check_out_time": "11:00"}'),
  
  ('Formosa Park Hotel & Apartamentos', 'formosa-park-hotel-apartamentos', 'Family-friendly hotel in Almancil with spacious apartments, beautiful gardens, and proximity to Quinta do Lago and Ria Formosa.', 'Family-friendly hotel with spacious apartments.', 'almancil', '{"star_rating": 5, "property_type": "Aparthotel", "amenities": ["Swimming Pool", "Gardens", "Restaurant", "Kids Activities", "Golf Nearby", "Tennis"], "room_types": ["Studio", "One Bedroom", "Two Bedroom Apartment"], "check_in_time": "15:00", "check_out_time": "11:00"}'),
  
  ('Prado Villas', 'prado-villas', 'Exclusive villa resort in Vilamoura offering private pool villas, personalized concierge, and premium living in a prime golf destination.', 'Exclusive villa resort with private pools.', 'vilamoura', '{"star_rating": 5, "property_type": "Villa Resort", "amenities": ["Private Pools", "Concierge", "Golf Nearby", "Chef Service", "Housekeeping", "Car Rental"], "room_types": ["2 Bedroom Villa", "3 Bedroom Villa", "4 Bedroom Villa"], "check_in_time": "16:00", "check_out_time": "10:00"}'),
  
  ('Dunas Douradas Beach Club', 'dunas-douradas-beach-club', 'Exclusive beachfront apartments in Vale do Lobo with direct beach access, elegant design, and prime Golden Triangle location.', 'Exclusive beachfront apartments in Vale do Lobo.', 'vale-do-lobo', '{"star_rating": 5, "property_type": "Beach Club", "amenities": ["Private Beach", "Swimming Pool", "Restaurant", "Tennis", "Golf Nearby", "Concierge"], "room_types": ["One Bedroom", "Two Bedroom", "Penthouse"], "check_in_time": "16:00", "check_out_time": "10:00"}'),
  
  ('Vila Joya', 'vila-joya-hotel', 'Ultra-exclusive boutique hotel in Albufeira home to 2-Michelin star restaurant, intimate spa, and personalized premium in stunning clifftop setting.', 'Ultra-exclusive boutique hotel with 2-Michelin star restaurant.', 'albufeira', '{"star_rating": 5, "property_type": "Boutique Hotel", "amenities": ["2 Michelin Star Restaurant", "Spa", "Private Beach", "Personalized Service", "Pool", "Gardens"], "room_types": ["Deluxe Suite", "Junior Suite", "Master Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Praia Verde Boutique Hotel', 'praia-verde-boutique-hotel', 'Boutique beach hotel near Castro Marim with eco-conscious design, pristine beach access, and relaxed atmosphere near the Spanish border.', 'Boutique beach hotel with eco-conscious design.', 'tavira', '{"star_rating": 5, "property_type": "Boutique Hotel", "amenities": ["Beach Access", "Eco-Design", "Restaurant", "Pool", "Spa", "Nature Trails"], "room_types": ["Garden Room", "Beach Suite", "Family Room"], "check_in_time": "15:00", "check_out_time": "11:00"}'),
  
  ('Morgado Golf & Country Club', 'morgado-golf-country-club', 'Golf-focused resort near Portimão offering championship courses, golf academy, and comfortable accommodations for golf enthusiasts.', 'Golf-focused resort with championship courses.', 'portimao', '{"star_rating": 5, "property_type": "Golf Resort", "amenities": ["Two Golf Courses", "Golf Academy", "Swimming Pool", "Restaurant", "Spa", "Tennis"], "room_types": ["Standard Room", "Deluxe Room", "Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('Penina Hotel & Golf Resort', 'penina-hotel-golf-resort', 'Historic golf resort in Portimão featuring Sir Henry Cotton-designed championship course, extensive facilities, and classic Portuguese hospitality.', 'Historic golf resort with championship course.', 'portimao', '{"star_rating": 5, "property_type": "Golf Resort", "amenities": ["Championship Golf", "Driving Range", "Tennis", "Pool", "Spa", "Multiple Restaurants"], "room_types": ["Classic Room", "Superior Room", "Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('Amendoeira Golf Resort', 'amendoeira-golf-resort', 'Modern golf resort near Silves featuring two championship courses designed by Christy O''Connor Jr and Nick Faldo.', 'Modern golf resort with two championship courses.', 'lagoa', '{"star_rating": 5, "property_type": "Golf Resort", "amenities": ["Two Championship Courses", "Golf Academy", "Pool", "Restaurant", "Gym", "Tennis"], "room_types": ["Resort Room", "Golf Villa", "Townhouse"], "check_in_time": "15:00", "check_out_time": "11:00"}'),
  
  ('Robinson Club Quinta da Ria', 'robinson-club-quinta-da-ria', 'All-inclusive premium club resort near Tavira with sports facilities, entertainment, and access to Ria Formosa and golf courses.', 'All-inclusive premium club resort near Tavira.', 'tavira', '{"star_rating": 5, "property_type": "Club Resort", "amenities": ["All-Inclusive", "Sports Facilities", "Golf Access", "Beach Shuttle", "Entertainment", "Spa"], "room_types": ["Double Room", "Family Room", "Suite"], "check_in_time": "15:00", "check_out_time": "10:00"}'),
  
  ('Vila Monte Farm House', 'vila-monte-farm-house', 'Boutique country hotel near Olhão offering authentic Algarve experience with organic farm, stunning design, and proximity to Ria Formosa.', 'Boutique country hotel with organic farm.', 'olhao', '{"star_rating": 5, "property_type": "Country Hotel", "amenities": ["Organic Farm", "Pool", "Spa", "Restaurant", "Gardens", "Cooking Classes"], "room_types": ["Garden Room", "Pool Room", "Suite"], "check_in_time": "15:00", "check_out_time": "11:00"}'),
  
  ('Aqua Pedra dos Bicos', 'aqua-pedra-dos-bicos', 'Adults-only design hotel in Albufeira Old Town with stunning ocean views, rooftop terrace, and vibrant location near beaches and nightlife.', 'Adults-only design hotel in Albufeira Old Town.', 'albufeira', '{"star_rating": 5, "property_type": "Design Hotel", "amenities": ["Adults Only", "Rooftop Terrace", "Pool", "Restaurant", "Bar", "Beach Access"], "room_types": ["Standard Room", "Sea View Room", "Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('Pestana Viking Beach & Spa Resort', 'pestana-viking-beach-spa-resort', 'Beachfront resort on Armação de Pêra Beach with direct beach access, comprehensive spa, and family-friendly facilities.', 'Beachfront resort with direct beach access.', 'armacao-de-pera', '{"star_rating": 5, "property_type": "Resort", "amenities": ["Private Beach", "Spa", "Pools", "Kids Club", "Restaurant", "Entertainment"], "room_types": ["Standard Room", "Sea View Room", "Suite"], "check_in_time": "15:00", "check_out_time": "12:00"}'),
  
  ('Pestana Delfim Beach & Golf Hotel', 'pestana-delfim-beach-golf-hotel', 'All-inclusive beach hotel in Alvor with golf access, extensive entertainment, and family-friendly atmosphere overlooking the sea.', 'All-inclusive beach hotel with golf access.', 'alvor', '{"star_rating": 5, "property_type": "Hotel", "amenities": ["All-Inclusive", "Golf Access", "Beach", "Pools", "Kids Club", "Entertainment"], "room_types": ["Standard Room", "Superior Room", "Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('Yellow Lagos Meia Praia Hotel', 'yellow-lagos-meia-praia-hotel', 'Contemporary beach hotel on Meia Praia Beach in Lagos with modern design, excellent facilities, and direct beach access.', 'Contemporary beach hotel on Meia Praia Beach.', 'lagos', '{"star_rating": 5, "property_type": "Beach Hotel", "amenities": ["Beach Access", "Pool", "Spa", "Restaurant", "Fitness Center", "Water Sports"], "room_types": ["Standard Room", "Superior Room", "Family Suite"], "check_in_time": "14:00", "check_out_time": "12:00"}'),
  
  ('Memmo Baleeira Hotel', 'memmo-baleeira-hotel', 'Design hotel in Sagres with minimalist aesthetics, ocean views, and proximity to some of the Algarve''s most dramatic beaches and surf spots.', 'Design hotel with minimalist aesthetics in Sagres.', 'sagres', '{"star_rating": 5, "property_type": "Design Hotel", "amenities": ["Ocean Views", "Pool", "Spa", "Restaurant", "Surf School", "Yoga"], "room_types": ["Garden Room", "Sea View Room", "Suite"], "check_in_time": "15:00", "check_out_time": "11:00"}')
  
) AS hotel(name, slug, description, short_description, city_slug, category_data)
WHERE NOT EXISTS (
  SELECT 1 FROM listings WHERE listings.slug = hotel.slug
);
