begin;

do $$
declare
  v_listing_id uuid;
  v_nearby_restaurants jsonb := $json$
[
  {
    "name": "Restaurante Ocean",
    "type": "Restaurant",
    "distance": "~0.7 km",
    "description": "Published AlgarveOfficial restaurant listing in Porches; approximate distance from Senhora da Rocha calculated from stored listing coordinates.",
    "href": "/listing/restaurante-ocean-almancil",
    "verification_status": "Published internal listing"
  },
  {
    "name": "Aladin Grill",
    "type": "Restaurant",
    "distance": "~0.8 km",
    "description": "Published AlgarveOfficial restaurant listing near Vila Vita Parc; approximate distance from Senhora da Rocha calculated from stored listing coordinates.",
    "href": "/listing/aladin-grill-lagoa",
    "verification_status": "Published internal listing"
  },
  {
    "name": "Atlântico",
    "type": "Restaurant",
    "distance": "~0.8 km",
    "description": "Published AlgarveOfficial restaurant listing near Vila Vita Parc; approximate distance from Senhora da Rocha calculated from stored listing coordinates.",
    "href": "/listing/atlantico-lagoa",
    "verification_status": "Published internal listing"
  },
  {
    "name": "O Leão de Porches",
    "type": "Restaurant",
    "distance": "~3.7 km",
    "description": "Published AlgarveOfficial restaurant listing in the Porches/Lagoa area; approximate distance from Senhora da Rocha calculated from stored listing coordinates.",
    "href": "/listing/o-leao-de-porches-lagoa",
    "verification_status": "Published internal listing"
  },
  {
    "name": "Bon Bon",
    "type": "Restaurant",
    "distance": "~5.1 km",
    "description": "Published AlgarveOfficial restaurant listing in Lagoa; approximate distance from Senhora da Rocha calculated from stored listing coordinates.",
    "href": "/listing/bon-bon-lagoa",
    "verification_status": "Published internal listing"
  }
]
$json$;
  v_nearby_attractions jsonb := $json$
[
  {
    "name": "Sand City",
    "type": "Family attraction",
    "distance": "~4.8 km",
    "description": "Published AlgarveOfficial family-attraction listing near Senhora da Rocha by stored listing coordinates.",
    "href": "/listing/sand-city-quarteira",
    "verification_status": "Published internal listing"
  },
  {
    "name": "Salgados Golf Course",
    "type": "Golf",
    "distance": "~5.2 km",
    "description": "Published AlgarveOfficial golf listing west of Senhora da Rocha by stored listing coordinates.",
    "href": "/listing/salgados-golf-course",
    "verification_status": "Published internal listing"
  },
  {
    "name": "Zoomarine Algarve",
    "type": "Family attraction",
    "distance": "~7.2 km",
    "description": "Published AlgarveOfficial family-attraction listing near Guia/Albufeira by stored listing coordinates.",
    "href": "/listing/zoomarine-algarve-albufeira",
    "verification_status": "Published internal listing"
  }
]
$json$;
  v_sources jsonb;
  v_notes jsonb;
  v_faq jsonb;
  v_patch jsonb;
begin
  select id
    into v_listing_id
  from public.listings
  where slug = 'praia-da-senhora-da-rocha-lagoa'
    and status = 'published';

  if v_listing_id is null then
    raise notice 'Published listing praia-da-senhora-da-rocha-lagoa not found; skipping update.';
    return;
  end if;

  select coalesce(category_data->'sources_used', '[]'::jsonb)
    into v_sources
  from public.listings
  where id = v_listing_id;

  v_sources := (
    select jsonb_agg(source_item)
    from (
      select source_item
      from jsonb_array_elements(v_sources) as source(source_item)
      where source_item->>'source_name' <> 'AlgarveOfficial internal published restaurant and attraction listings'
      union all
      select jsonb_build_object(
        'source_name', 'AlgarveOfficial internal published restaurant and attraction listings',
        'source_url', 'https://algarveofficial.com/listing/praia-da-senhora-da-rocha-lagoa',
        'facts_verified', jsonb_build_array(
          'Nearby restaurant and attraction cards link only to internally published AlgarveOfficial listing slugs checked on 18 May 2026',
          'Approximate nearby distances calculated from internal listing coordinates for Senhora da Rocha and the linked listings',
          'No external restaurant, attraction or competitor website links were added'
        )
      )
    ) as sources
  );

  select coalesce(category_data->'verification_notes', '[]'::jsonb)
    into v_notes
  from public.listings
  where id = v_listing_id;

  v_notes := (
    select jsonb_agg(note_item)
    from (
      select note_item
      from jsonb_array_elements(v_notes) as note(note_item)
      where note_item <> to_jsonb('Nearby restaurants and attractions are intentionally left to internal published AlgarveOfficial business/attraction cards generated by the app; no external competitor website cards were added.'::text)
      union all
      select to_jsonb('Nearby restaurant and attraction cards were added only where a published internal AlgarveOfficial listing exists; approximate distances are calculated from stored listing coordinates.'::text)
      union all
      select to_jsonb('No external restaurant, attraction or competitor website links were added.'::text)
    ) as notes
  );

  select coalesce(category_data->'faq_items', '[]'::jsonb)
    into v_faq
  from public.listings
  where id = v_listing_id;

  v_faq := (
    select jsonb_agg(faq_item)
    from (
      select faq_item
      from jsonb_array_elements(v_faq) as faq(faq_item)
      where faq_item->>'question' not in (
        'Are there restaurants near Praia da Senhora da Rocha?',
        'What attractions are near Praia da Senhora da Rocha?'
      )
      union all
      select jsonb_build_object(
        'question', 'Are there restaurants near Praia da Senhora da Rocha?',
        'answer', 'Yes. AlgarveOfficial has internally published nearby restaurant listings including Restaurante Ocean, Aladin Grill, Atlântico, O Leão de Porches and Bon Bon. Distances are approximate and calculated from stored listing coordinates.'
      )
      union all
      select jsonb_build_object(
        'question', 'What attractions are near Praia da Senhora da Rocha?',
        'answer', 'Nearby internally published AlgarveOfficial attraction listings include Sand City, Salgados Golf Course and Zoomarine Algarve. Distances are approximate and calculated from stored listing coordinates.'
      )
    ) as faqs
  );

  v_patch := jsonb_build_object(
    'nearby_restaurants', v_nearby_restaurants,
    'nearby_attractions', v_nearby_attractions,
    'sources_used', coalesce(v_sources, '[]'::jsonb),
    'verification_notes', coalesce(v_notes, '[]'::jsonb),
    'faq_items', coalesce(v_faq, '[]'::jsonb)
  );

  update public.listings
     set category_data = jsonb_set(
           coalesce(category_data, '{}'::jsonb) || v_patch,
           '{localized_content,en}',
           (coalesce(category_data, '{}'::jsonb) || v_patch) - 'localized_content',
           true
         ),
         updated_at = now()
   where id = v_listing_id;
end $$;

commit;
