begin;

do $$
declare
  v_listing_id uuid;
  v_nearby_restaurants jsonb := $json$
[
  {
    "name": "Aladin Grill",
    "type": "Restaurant",
    "distance": "~2.2 km",
    "description": "Published AlgarveOfficial restaurant listing near Vila Vita Parc; approximate distance from Albandeira calculated from stored listing coordinates.",
    "href": "/listing/aladin-grill-lagoa",
    "verification_status": "Published internal listing"
  },
  {
    "name": "Atlântico",
    "type": "Restaurant",
    "distance": "~2.2 km",
    "description": "Published AlgarveOfficial restaurant listing near Vila Vita Parc; approximate distance from Albandeira calculated from stored listing coordinates.",
    "href": "/listing/atlantico-lagoa",
    "verification_status": "Published internal listing"
  },
  {
    "name": "Ocean Restaurant",
    "type": "Restaurant",
    "distance": "~2.2 km",
    "description": "Published AlgarveOfficial restaurant listing near Vila Vita Parc; approximate distance from Albandeira calculated from stored listing coordinates.",
    "href": "/listing/ocean-lagoa",
    "verification_status": "Published internal listing"
  },
  {
    "name": "Bon Bon",
    "type": "Restaurant",
    "distance": "~4.0 km",
    "description": "Published AlgarveOfficial restaurant listing in Lagoa; approximate distance from Albandeira calculated from stored listing coordinates.",
    "href": "/listing/bon-bon-lagoa",
    "verification_status": "Published internal listing"
  },
  {
    "name": "O Leão de Porches",
    "type": "Restaurant",
    "distance": "~4.1 km",
    "description": "Published AlgarveOfficial restaurant listing in the Porches/Lagoa area; approximate distance from Albandeira calculated from stored listing coordinates.",
    "href": "/listing/o-leao-de-porches-lagoa",
    "verification_status": "Published internal listing"
  }
]
$json$;
  v_nearby_attractions jsonb := $json$
[
  {
    "name": "Sand City",
    "type": "Family attraction",
    "distance": "~4.6 km",
    "description": "Published AlgarveOfficial family-attraction listing near Albandeira by stored listing coordinates.",
    "href": "/listing/sand-city-quarteira",
    "verification_status": "Published internal listing"
  }
]
$json$;
  v_sources jsonb;
  v_notes jsonb;
  v_faq jsonb;
  v_patch jsonb;
begin
  select id
    into v_listing_id
  from public.listings
  where slug = 'praia-da-albandeira-lagoa'
    and status = 'published';

  if v_listing_id is null then
    raise notice 'Published listing praia-da-albandeira-lagoa not found; skipping update.';
    return;
  end if;

  select coalesce(category_data->'sources_used', '[]'::jsonb)
    into v_sources
  from public.listings
  where id = v_listing_id;

  v_sources := (
    select jsonb_agg(source_item)
    from (
      select source_item
      from jsonb_array_elements(v_sources) as source(source_item)
      where source_item->>'source_name' <> 'AlgarveOfficial internal published restaurant and attraction listings'
      union all
      select jsonb_build_object(
        'source_name', 'AlgarveOfficial internal published restaurant and attraction listings',
        'source_url', 'https://algarveofficial.com/listing/praia-da-albandeira-lagoa',
        'facts_verified', jsonb_build_array(
          'Nearby restaurant and attraction cards link only to internally published AlgarveOfficial listing slugs checked on 18 May 2026',
          'Approximate nearby distances calculated from internal listing coordinates for Albandeira and the linked listings',
          'No external restaurant, attraction or competitor website links were added'
        )
      )
    ) as sources
  );

  select coalesce(category_data->'verification_notes', '[]'::jsonb)
    into v_notes
  from public.listings
  where id = v_listing_id;

  v_notes := (
    select jsonb_agg(note_item)
    from (
      select note_item
      from jsonb_array_elements(v_notes) as note(note_item)
      where note_item <> to_jsonb('Nearby restaurants and attractions are intentionally left to internal published AlgarveOfficial business/attraction cards generated by the app; no external competitor website cards were added.'::text)
      union all
      select to_jsonb('Nearby restaurant and attraction cards were added only where a published internal AlgarveOfficial listing exists; approximate distances are calculated from stored listing coordinates.'::text)
      union all
      select to_jsonb('No external restaurant, attraction or competitor website links were added.'::text)
    ) as notes
  );

  select coalesce(category_data->'faq_items', '[]'::jsonb)
    into v_faq
  from public.listings
  where id = v_listing_id;

  v_faq := (
    select jsonb_agg(faq_item)
    from (
      select
        case
          when faq_item->>'question' = 'Are there restaurants near Praia da Albandeira?' then
            jsonb_set(
              faq_item,
              '{answer}',
              to_jsonb('Yes. AlgarveOfficial has internally published nearby restaurant listings including Aladin Grill, Atlântico, Ocean Restaurant, Bon Bon and O Leão de Porches. Distances are approximate and calculated from stored listing coordinates.'::text),
              true
            )
          else faq_item
        end as faq_item
      from jsonb_array_elements(v_faq) as faq(faq_item)
    ) as faqs
  );

  v_patch := jsonb_build_object(
    'nearby_restaurants', v_nearby_restaurants,
    'nearby_attractions', v_nearby_attractions,
    'sources_used', coalesce(v_sources, '[]'::jsonb),
    'verification_notes', coalesce(v_notes, '[]'::jsonb),
    'faq_items', coalesce(v_faq, '[]'::jsonb)
  );

  update public.listings
     set category_data = jsonb_set(
           coalesce(category_data, '{}'::jsonb) || v_patch,
           '{localized_content,en}',
           (coalesce(category_data, '{}'::jsonb) || v_patch) - 'localized_content',
           true
         ),
         updated_at = now()
   where id = v_listing_id;
end $$;

commit;
